config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root "lists#new"
  resources :lists do
    post :update_current_participant
    resources :items do
      resources :participants, only: %i[create destroy], controller: "bringers"
    end
    resources :participants
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  has_many :item_participants
  has_many :participants, through: :item_participants
end

app/models/item_participant.rb
class ItemParticipant < ApplicationRecord
  belongs_to :participant
  belongs_to :item
  validates_uniqueness_of :participant_id, :scope => :item_id
end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :title
  has_many :items, dependent: :destroy
  has_many :participants, dependent: :destroy
end

app/models/participant.rb
class Participant < ApplicationRecord
  validates_presence_of :name
  belongs_to :list
  has_many :item_participants, dependent: :destroy
  has_many :items, through: :item_participants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bringers_controller.rb
class BringersController < ApplicationController
  before_action :set_list
  before_action :set_item

  def create
    @item.participants << Participant.find(params[:id])
    redirect_to @list
  end

  def destroy
    @item.participants.delete(Participant.find(params[:id]))
    redirect_to @list
  end

  private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list

  def create
    @list.items.create!(params.required(:item).permit(:title))
    redirect_to @list
  end

  def index
    redirect_to list_path(@list)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy

    redirect_to @list
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :get_current_participant_id
  before_action :is_participant_logged?
  before_action :set_list, :only => [:show]

  def new
    @list = List.new
  end
  
  def show
  end

  def create
    @list = List.create(list_params)
    redirect_to list_path(@list)
  end
  
  def set_list
    @list = List.find(params[:id])
  end

  def index
    redirect_to root_path
  end

  def is_participant_logged?
    return session[params[:id]].present?
  end

  def get_current_participant_id
    @current_participant_id = session[params[:id]]&.to_i
  end

  def update_current_participant
    session[params[:list_id]] = params[:participant_id]
    @current_participant_id = params[:participant_id].to_i
    redirect_to list_path(List.find(params[:list_id]))
  end

  private
  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_list

  def create
    participant = @list.participants.create!(set_params)
    participant.color = "%06x" % (rand * 0xffffff)
    participant.save
    
    redirect_to @list
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end

    def set_params
      params.required(:participant).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_participants_helper.rb
module ItemParticipantsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/items/_form.html.slim
= form_with model: [ list, item ], class: "grid gap-2" do |f| 
  = f.hidden_field :list_id, value: list.id
  = f.text_field :title, class: "h-12 border-2 border-black", placeholder: t("item.form.add.placeholder")
  = f.submit class: "hidden"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Hotlist
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    main.container.mx-auto.py-8
      = yield

app/views/lists/_form.html.slim
= form_for list do |f| 
  = f.text_field :title, placeholder: "Name your list and press Enter", class: "border-2 border-black w-full"
  = f.submit class: "hidden"

app/views/lists/_items.html.slim
= content_tag :ul, class: 'flex flex-col-reverse gap-4' do
  - list.items.each do |item|
    li.flex.items-strech.justify-between.border-2.border-black.bg-gray-200
      .flex-1.flex.items-center.gap-2.p-4
        .font-bold = item.title
        - if @current_participant_id
          - if item.participants.pluck(:id).include?(@current_participant_id)
            = button_to list_item_participant_path(item_id: item.id, list_id: list.id, id: @current_participant_id ), method: :delete do
              .text-sm = t('item.bringer.remove')
          - else
            = button_to list_item_participants_path(item_id: item.id, list_id: list.id, id: @current_participant_id ), method: :post do
              .text-sm = t('item.bringer.add')
      .flex.items-strech
        - if item.participants.any?
          .border-l-2.border-black.flex.items-center.p-4.gap-2
            - item.participants.each do |participant|
              = render Participants::AvatarComponent.new(name: participant.name, color: participant.color)
        .flex.items-center.border-black.border-l-2.px-4
          = link_to list_item_path(id: item.id, list_id: list.id), data: { turbo_method: :delete, turbo_confirm: t('item.delete.confirm') } do
            svg width="32" height="32" viewBox="0 0 24 24"
              path fill="currentColor" d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"

app/views/lists/_participants.html.slim
= content_tag :ul, class: "inline-flex gap-2 flex-1" do
  - list.participants.each do |participant|
    = button_to list_update_current_participant_path(list_id: list.id, participant_id: participant.id)
      = render Participants::TagComponent.new(name: participant.name, color: participant.color, participant_id: participant.id, current_participant_id: @current_participant_id)

app/views/lists/new.html.slim
.min-h-screen.flex.items-center.justify-center.-mt-8
  .w-full.flex.gap-4.justify-center
    h1.text-center.font-bold.text-4xl Hotlist
    div class="w-[500px]"
      = render "lists/form", :list => List.new

app/views/lists/show.html.slim
.grid.gap-8
  h1.font-semibold.text-4xl = @list.title

  / Participants
  .bg-gray-100.p-8.pt-16.flex.gap-4.items-center.relative.mt-8.border-2.border-gray-200
    .bg-gray-200.absolute.-top-6.left-4
      = render "participants/form", :list => @list, :participant => Participant.new
    - if @list.participants.empty?
      .text-sm.italic.text-center = t('lists.show.participants.empty')
    - else
      div
        h2.font-bold = t('lists.show.current_participant.title')
        .text-sm = t('lists.show.current_participant.instruction')
      = render "lists/participants", :list => @list

  / List
  .grid.gap-4
    = render "items/form", :list => @list, :item => Item.new
    - if @list.items.empty?
      .text-xl.text-center.w-full -
    - else
      = render "lists/items", :list => @list

   

app/views/participants/_form.html.slim
= form_with model: [ list, participant ], class: "flex" do |f| 
  = f.hidden_field :list_id, value: list.id
  = f.text_field :name, class: "h-12 border-2 border-black min-w-[280px]", placeholder: t("participant.form.add.placeholder")
  = f.submit t("participant.form.add.submit"), class: "bg-black text-white px-4"